// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekctfpcglgphystvzwwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrY3RmcGNnbGdwaHlzdHZ6d3d2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NzA4OTgsImV4cCI6MjA2NzQ0Njg5OH0.Zfc_Mlq-z07iefRUca9DtpUQOjVmt1qOJ4dy4O30WTw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});